version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # `yarn build` for production
    command: yarn start
    # `NODE_ENV=production` for production
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
    # Port 1235 for HMR - remove for production
    ports:
      - 1234:1234
      - 1235:1235
    working_dir: /app/frontend
    # Shared files for HMR - remove for production
    volumes:
      - ./frontend:/app/frontend
  # TODO
  arangodb:
    image:
      arangodb
    ports:
      - 8529:8529
    volume:
      - ./tmp/arangodb:/var/liv/arangdodb3
    enviroment:
      - ARANGO_ROOT_PASSWORD=dogport
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/backend
      ports:
        - 5000:5000


